//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.08.13 at 03:33:25 PM TRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://soap-stocks.up.railway.app", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.soap_stocks_up_railway;
